### ISSUE TITLE
Chức năng "Xuất mục đã lưu trên Facebook" chỉ hoạt động 1 lần sau khi cài đặt extension

### ISSUE THREAD

**Issue by kot721** [HoangTran0410/useful-script#11]
Cảm ơn bạn vì việc tạo ra extension này. Nó đã giúp mình nhiều trong công việc hàng ngày, hiện mình đang xài tính năng "Xuất mục đã lưu trên Facebook" nhưng đang gặp lỗi hy vọng bạn khắc phục sớm. Cám ơn bạn nhiều.

Sau khi cài đặt extension lần đầu thì tính năng "Xuất mục đã lưu trên Facebook" hoạt động bình thường và có thể sử dụng tính năng này một lần. Tuy nhiên, sau khi tắt trình duyệt và mở lại, chức năng này không còn hoạt động nữa. Thay vào đó, nhận được một lỗi "ERROR: TypeError: (intermediate value) is not iterable." Lỗi này xuất hiện mỗi khi sử dụng tính năng.

Các bước để làm xuất hiện lỗi:
1. Cài đặt extension trên trình duyệt của bạn.
2. Sử dụng chức năng "Xuất mục đã lưu trên Facebook" thành công lần đầu.
3. Tắt trình duyệt.
4. Mở lại trình duyệt.
5. Thử sử dụng lại chức năng "Xuất mục đã lưu trên Facebook."

**Comment by HoangTran0410** [comment]
mình sử dụng vẫn thấy tải được mà ta, tải về file data json á.
Mình có cập nhật lại, cấu trúc lưu khác.
Bạn cài lại extension rồi thử lại nha.
