### ISSUE TITLE
Không thể xem được tin nhắn đã gỡ bản 1.6

### ISSUE THREAD

**Issue by KietTezend** [HoangTran0410/useful-script#14]
![image](https://github.com/HoangTran0410/useful-script/assets/90176660/e5cc3a27-d714-4de2-a24f-01b091bf2168)

**Comment by HoangTran0410** [comment]
![image](https://github.com/HoangTran0410/useful-script/assets/36368107/24cc75e6-e46c-4b91-9d70-f30a2db3ef7f)

Mình test thử thấy chức năng vẫn chay tốt á.
Bạn xoá extension cài lại bản 1.61 thử nha.
