### ISSUE TITLE
Douyin Update

### ISSUE THREAD

**Issue by linquocte** [HoangTran0410/useful-script#6]
Chào bạn, xin cảm ơn vì extension của đã giúp mình rất nhiều trong công việc. Hiện tại, chức năng tải full video từ Douyin đã không thể sử dụng được nữa (theo mình nghĩ Douyin đã update gì đó). Mong bạn kiểm tra lại. Xin chân thành cảm ơn vì đóng góp của bạn. 
<img width="267" alt="image" src="https://user-images.githubusercontent.com/89297828/227776794-b86cd1e9-98ab-49f2-905a-21c8fcafb3e5.png">

**Comment by HoangTran0410** [comment]
Douyin đã update api của họ rồi.
Chức năng này hiện tại không còn sử dụng được nữa.

**Comment by HoangTran0410** [comment]
Đã update lại chức năng tải video của user douyin rồi nhé. Bạn tải cài lại extendsion là được nha.

Code fix tham khảo từ: https://github.com/diepvantien/douyin-dowload-all-video
