### ISSUE TITLE
Tải hàng loạt

### ISSUE THREAD

**Issue by Albertaku** [HoangTran0410/useful-script#7]
chỉ cần tải xuống tệp txt với các liên kết sau https://scontent.fmid1-3.fna.fbcdn.net/v/t1.6435-9/118750244_360647444960094_7036524159523594047_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid0=anc832 vIAX9.fedg1&scontent -3.fna&oh=00_AfBmYg7rMoZGa_mKJWpfPHhvohhq-738ZQxBGTAZ5EQsNw&oe=646B9DD6 Tôi làm cách nào để tải xuống tất cả các hình ảnh?

**Comment by HoangTran0410** [comment]
You can import file that contains these url into other download manager app ([idm](https://www.internetdownloadmanager.com/) or [fdm](https://www.freedownloadmanager.org/download.htm)). 

It will download those images for you, very fast.
