### ISSUE TITLE
text to speed

### ISSUE THREAD

**Issue by lucthienphong1120** [HoangTran0410/useful-script#8]
tôi thấy đây là 1 tính năng khá là hay,

bạn có thể làm text to speed 1 đoạn văn bản hoặc trang web ko

thay vì mấy trang tài liệu đọc nhiều cũng hơi chán :v có đọc hộ thì tốt (anh/việt)

**Comment by HoangTran0410** [comment]
Chức năng này nếu tự làm thì khá là khó, do phải tìm api nào free, ko bị giới hạn bla bla.
Nếu tìm được thì làm chức năng này ngon luôn 💯

**Comment by lucthienphong1120** [comment]
@HoangTran0410  ông thử nghiên cứu 1 số source bên j2 á https://j2team.dev/tools/text-to-speech
hôm trc cx thấy 1 người khác share tương tự mà qua r :v

**Comment by HoangTran0410** [comment]
cảm ơn bạn, tool của j2team đã khá hoàn chỉnh, nên mình đã thêm chức năng trỏ tới trang web của j2team. Thay đổi có thể được xem tại đây:

https://github.com/HoangTran0410/useful-script/commit/3fed6b0884ab21d465ab5a83c2583079a3697b00
